language: ruby
rvm:
  - rvm 2.2.1
  - rvm 2.2.2

install:
  - bundle

env:
  global:
    - TWILIO_ACCOUNT_SID=ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    - TWILIO_AUTH_TOKEN=TWILIOAUTHTOKEN00000
    - TWILIO_NUMBER=+12345555555
    - BOB_NUMBER=+1234567823
    - ALICE_NUMBER=+1234567000
