default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/taskrouter_development.sqlite3

test:
  <<: *default
  database: db/taskrouter_test.sqlite3

production:
  <<: *default
  database: db/taskrouter_production.sqlite3
